/* Generated by startup_generator */
// referenced from https://github.com/avislab/STM32F103/blob/master/Example_ADC/cmsis_boot/startup/startup_stm32f10x_md.c
//           and stm32f030-based startup_ files.
#include <stm32f10x.h>

extern void _estack(void);  // to force type checking
void Reset_Handler(void);
void Default_Handler (void) { while(1); }

void __attribute__ ((weak)) __libc_init_array(void){}

//-- Linker supplied pointers
extern unsigned long _sidata;
extern unsigned long _sdata;
extern unsigned long _edata;
extern unsigned long _sbss;
extern unsigned long _ebss;

//-- Function prototypes
extern int main(void);
void Reset_Handler(void);


void Reset_Handler(void) {
	unsigned long *src, *dst;
	src = &_sidata;
	dst = &_sdata;

	//-- Copy data segment from flash to SRAM
	while (dst < &_edata)
		*(dst++) = *(src++);

	//-- Zero bss
	dst = &_sbss;
	while (dst < &_ebss) 
		*(dst++) = 0;

	//-- setup the uC system
	SystemInit();
	__libc_init_array();		// initialize?? 
	
	//-- go to main
	main();
	while(1) {}
}

/* Vector Table */
void NMI_Handler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void HardFault_Handler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void MemMange_Handler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void BusFault_Handler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void UsageFault_Handler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void SVC_Handler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void DebugMon_Handler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void PendSV_Handler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void SysTick_Handler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void WWDG_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void PVD_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void TAMPER_STAMP_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void RTC_WKUP_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void FLASH_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void RCC_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void EXTI0_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void EXTI1_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void EXTI2_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void EXTI3_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void EXTI4_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void DMA1_Channel1_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void DMA1_Channel2_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void DMA1_Channel3_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void DMA1_Channel4_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void DMA1_Channel5_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void DMA1_Channel6_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void DMA1_Channel7_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void ADC1_2_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void USB_HP_CAN1_TX_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void USB_LP_CAN1_RX0_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void CAN1_RX1_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void CAN1_SCE_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void EXTI9_5_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void TIM1_BRK_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void TIM1_UP_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void TIM1_TRG_COM_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void TIM1_CC_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void TIM2_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void TIM3_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void TIM4_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void I2C1_EV_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void I2C1_ER_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void I2C2_EV_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void I2C2_ER_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void SPI1_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void SPI2_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void USART1_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void USART2_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void USART3_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void EXTI15_10_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void RTCAlarm_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void USBWakeUp_IRQHandler (void) __attribute__ ((weak,  alias ("Default_Handler")));
void BootRAM (void) __attribute__ ((weak,  alias ("Default_Handler")));



__attribute__ ((used,section(".isr_vector")))
void (* const g_pfnVectors[])(void) = {
  [0]  = _estack,
  [1]  = Reset_Handler,
  [2]  = NMI_Handler,
  [3]  = HardFault_Handler,
  [4]  = MemMange_Handler,
  [5]  = BusFault_Handler,
  [6]  = UsageFault_Handler,
  [11] = SVC_Handler,
  [12] = DebugMon_Handler,
  [14] = PendSV_Handler,
  [15] = SysTick_Handler,
  [16] = WWDG_IRQHandler,
  [17] = PVD_IRQHandler,
  [18] = TAMPER_STAMP_IRQHandler,
  [19] = RTC_WKUP_IRQHandler,
  [20] = FLASH_IRQHandler,
  [21] = RCC_IRQHandler,
  [22] = EXTI0_IRQHandler,
  [23] = EXTI1_IRQHandler,
  [24] = EXTI2_IRQHandler,
  [25] = EXTI3_IRQHandler,
  [26] = EXTI4_IRQHandler,
  [27] = DMA1_Channel1_IRQHandler,
  [28] = DMA1_Channel2_IRQHandler,
  [29] = DMA1_Channel3_IRQHandler,
  [30] = DMA1_Channel4_IRQHandler,
  [31] = DMA1_Channel5_IRQHandler,
  [32] = DMA1_Channel6_IRQHandler,
  [33] = DMA1_Channel7_IRQHandler,
  [34] = ADC1_2_IRQHandler,
  [35] = USB_HP_CAN1_TX_IRQHandler,
  [36] = USB_LP_CAN1_RX0_IRQHandler,
  [37] = CAN1_RX1_IRQHandler,
  [38] = CAN1_SCE_IRQHandler,
  [39] = EXTI9_5_IRQHandler,
  [40] = TIM1_BRK_IRQHandler,
  [41] = TIM1_UP_IRQHandler,
  [42] = TIM1_TRG_COM_IRQHandler,
  [43] = TIM1_CC_IRQHandler,
  [44] = TIM2_IRQHandler,
  [45] = TIM3_IRQHandler,
  [46] = TIM4_IRQHandler,
  [47] = I2C1_EV_IRQHandler,
  [48] = I2C1_ER_IRQHandler,
  [49] = I2C2_EV_IRQHandler,
  [50] = I2C2_ER_IRQHandler,
  [51] = SPI1_IRQHandler,
  [52] = SPI2_IRQHandler,
  [53] = USART1_IRQHandler,
  [54] = USART2_IRQHandler,
  [55] = USART3_IRQHandler,
  [56] = EXTI15_10_IRQHandler,
  [57] = RTCAlarm_IRQHandler,
  [58] = USBWakeUp_IRQHandler,
  [66] = BootRAM,
};
